version: '3'

services:
# postgres db
  db:
    container_name: postgres_database
    image: "postgres:14.0"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'postgres'

# graphql api
  backend:
    container_name: backend_liveworks
    build: ./backend
    restart: always
    volumes: 
      - ./backend:/backend
      - images:/images
    ports: 
      - "4000:4000"
    depends_on:
      - db
    environment:
      DB_HOST: 'http://db:5432'
      DB_NAME: 'postgres'
      DB_PORT: '5432'
      DB_USER: 'test'
      DB_PASS: 'test'
      NGINX_HOST: 'localhost'
      NGINX_PORT: 8080
  
  # using this to serve static content like images etc
  media:
    image: nginx
    restart: always
    volumes: 
      - images:/usr/share/nginx/html/images:ro
    ports: 
      - "8080:80"

# React app
  frontend:
    container_name: frontend_liveworks
    build: ./frontend
    restart: always
    volumes:
      - ./frontend:/frontend
    ports: 
      - "3000:3000"
    depends_on:
      - backend
    environment: 
      CHOKIDAR_USEPOLLING: "true"

volumes: 
  images:
  pgdata: